### PR TITLE
Add add_bam_readcount_to_vcf to tumor_only workflow

### PR DESCRIPTION
**Pull request by susannasiebert**
I ran a test for the add_bam_readcount_to_vcf.cwl with the included add_bam_readcount_to_vcf.yaml. I can move the test data files to the example_data directory, if desired. I haven't tested the changes to the tumor only workflow.

### CODE REVIEW

**Comment by susannasiebert** [comment]
I ran this locally using the `/gscmnt/gc2585/fulton/model_data/cc994b38f1454a009117e1751b7152f3/build2b978d7996cd4cf096381a1edc78884a/inputs.yaml` yaml and it finished successfully. Output is at `/gscmnt/gc2764/cad/ssiebert/toil_test/out/lsf4/`

**Comment by jasonwalker80** [comment]
I see `AF` so that's good!

**Comment by susannasiebert** [comment]
Yeah, the test workflow I did ended after add_bam_readcount_to_vcf. I'm running it locally all the way through just to make sure there aren't any downstream failures but I think this should be ok to merge.

**Comment by susannasiebert** [comment]
I had to remove certain fields from the variants to table step but I got it to succeed. Successful output is at `/gscmnt/gc2764/cad/ssiebert/toil_test/out/lsf5`

@jasonwalker80 can you check that the reduced list of field is ok for this workflow.

**Pull request merged**
