### PR TITLE
New Germline WGS workflow for alignment, QC, HaplotypeCaller, VEP.

### PR DESCRIPTION
**Pull request by tmooney**
Based on the Exome workflow, but with the WGS alignment process instead!

### CODE REVIEW

**Comment by tmooney** [comment]
As suggested, I'll revise this PR after #317 and #319 have been addressed.  That will simplify this new workflow quite a bit!

**Comment by jasonwalker80** [comment]
FYI, #317 and #319 are both merged.

**Comment by tmooney** [comment]
Updated this PR to account for the other merged changes.

**Comment by dufeiyu** [comment]
+1

**Pull request merged**
